bot_token:1270066629:AAGEVnYGEvAWH1FHhegrzwopJPj7qNgs6zM
telegraph_token:094bb86c32334ab46c90f40b1af08fd0dc6cd7ce0e96cd88390fb5c3367f
update_interval: 5
mysql:
  host: 127.0.0.1
  port: 3306
  user: user
  password: pwd
  database: flowerss
sqlite:
  path: ./data.db
